dist: focal
sudo: true
language: python
env:
  - SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=disk
matrix:
  include:
  - python: 3.10
    addons:
    -  apt:
    -    packages:
          - graphviz
before_install:

install: 
    - pip install -r requirements.txt
    - export PYTHONPATH=src
script:
    - python setup.py unittests
