dist: xenial
sudo: true
language: python
env:
  - SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=disk
matrix:
  include:
  - python: 3.7.3
    name: "Py.3.7.3-Sph.2.1"
    env: sphinxconstraint=">=2.1"
    addons:
    -  apt:
    -    packages:
          - graphviz
  - python: 3.8.1
    name: "Py.3.8.1-Sph.2.3"
    env: sphinxconstraint=">=2.3"
    addons:
    -  apt:
    -    packages:
          - graphviz
before_install:

install: 
    - pip install -r requirements.txt
    - export PYTHONPATH=src
script:
    - python setup.py unittests
