name: Check URLs

on:
  pull_request:
    branches: [main]
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: urls-checker-code
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: teachpyx
        file_types: .md,.py,.rst,.ipynb
        print_all: false
        timeout: 5
        retry_count# : 3
        # exclude_urls: https://dumps.wikimedia.org/other/pageviews/%Y/%Y-%m/pageviews-%Y%m%d-%H0000.gz,https://dumps.wikimedia.org/frwiki/latest/latest-all-titles-in-ns0.gz
        exclude_patterns: https://dumps.wikimedia.org/
        # force_pass : true

    - name: urls-checker-docs
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: _doc
        file_types: .md,.py,.rst,.ipynb
        print_all: false
        timeout: 5
        retry_count# : 3
        exclude_urls: https://github.com/sdpython/teachpyx/raw/td/_data/,https://ast.wikipedia.org/wiki/Python,https://www.data.gouv.fr/fr/datasets/r/4acad602-d8b1-4516-bc71-7d5574d5f33e,http://www.xavierdupre.fr/enseignement/complements/,https://www.gutenberg.org/cache/epub/12587/pg12587.txt,https://www.insee.fr/fr/statistiques/fichier/2407910/,https://castor-informatique.fr,https://hal.archives-ouvertes.fr/hal-00990252/document,https://github.com/onnx/models/raw/main/vision/classification/mobilenet/model/mobilenetv2-12.onnx,https://arxiv.org/ftp/arxiv/papers/1510/1510.04863.pdf,https://hal.science/hal-01125940,https://www.data.gouv.fr/fr/datasets/r/63352e38-d353-4b54-bfd1-f1b3ee1cabd7,https://github.com/sdpython/teachpyx/raw/main/_data/examen2021.zip,https://www.enseignement.polytechnique.fr/informatique/INF423/uploads/Main/poly-good.pdf
        exclude_patterns: http://www.xavierdupre.fr/enseignement/complements,https://github.com/sdpython/teachpyx/blob/main/_doc/practice/exams/,https://github.com/sdpython/teachpyx/raw/main/_data/,https://www.data.gouv.fr/fr/datasets/r/e3d83ab3-dc52-4c99-abaf-8a38050cc68c,https://github.com/onnx/models/raw/main/vision/classification/mobilenet/model/mobilenetv2-12.onnx,https://www.data.gouv.fr/fr/datasets/r/63352e38-d353-4b54-bfd1-f1b3ee1cabd7,https://github.com/sdpython/teachpyx/raw/main/_data/examen2021.zip
        # force_pass : true
