name: RST Check

on: [push, pull_request]

jobs:
  build_wheels:
    name: rstcheck ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Install rstcheck
        run: python -m pip install sphinx tomli rstcheck[toml,sphinx]

      - name: rstcheck
        run: find _doc teachpyx -name "*.rst" ! -path "_doc/articles/2026/2026-03-15-route2026-ml.rst" -print0 | xargs -0 rstcheck
